// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrsldNiYTbm_ViUk_ZVPr71LYf5DwAhkU',
    appId: '1:908213207719:android:f853f2da87931508b9d182',
    messagingSenderId: '908213207719',
    projectId: 'insta-clone-qthanh-app',
    storageBucket: 'insta-clone-qthanh-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANPqLQiL3LAsUvrsRSpkLYEDcuVznQg4g',
    appId: '1:908213207719:ios:d2c2500d2492771fb9d182',
    messagingSenderId: '908213207719',
    projectId: 'insta-clone-qthanh-app',
    storageBucket: 'insta-clone-qthanh-app.firebasestorage.app',
    iosClientId: '908213207719-02a4t5p6mjqpov1rhdelhshdm283qa2f.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.instagramCloneQthanh',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBiLQnnMRkod4z5u9Vwd23coxYv2poMN8',
    appId: '1:908213207719:web:70d47962d80e7147b9d182',
    messagingSenderId: '908213207719',
    projectId: 'insta-clone-qthanh-app',
    authDomain: 'insta-clone-qthanh-app.firebaseapp.com',
    storageBucket: 'insta-clone-qthanh-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANPqLQiL3LAsUvrsRSpkLYEDcuVznQg4g',
    appId: '1:908213207719:ios:d2c2500d2492771fb9d182',
    messagingSenderId: '908213207719',
    projectId: 'insta-clone-qthanh-app',
    storageBucket: 'insta-clone-qthanh-app.firebasestorage.app',
    iosClientId: '908213207719-02a4t5p6mjqpov1rhdelhshdm283qa2f.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.instagramCloneQthanh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBiLQnnMRkod4z5u9Vwd23coxYv2poMN8',
    appId: '1:908213207719:web:f053c4105151d0fcb9d182',
    messagingSenderId: '908213207719',
    projectId: 'insta-clone-qthanh-app',
    authDomain: 'insta-clone-qthanh-app.firebaseapp.com',
    storageBucket: 'insta-clone-qthanh-app.firebasestorage.app',
  );

}